version: "3.8"

services:
  postgres:
    image: postgres:15.5
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=atv
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=**123456789**
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
